# Generated by Django 3.1.4 on 2020-12-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomat_fwd_chaining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aturan',
            fields=[
                ('kode_aturan', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('konten', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gejala',
            fields=[
                ('kode_gejala', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('konten', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Fakta',
        ),
    ]
