# Generated by Django 3.1.4 on 2020-12-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomat_fwd_chaining', '0002_auto_20201229_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='gejala',
            name='pilihan',
            field=models.CharField(choices=[(0, 'salah'), (1, 'benar')], default=0, max_length=10),
        ),
    ]
