# Generated by Django 3.1.4 on 2020-12-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomat_fwd_chaining', '0004_auto_20201229_2005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aturan',
        ),
    ]
