# Generated by Django 3.1.4 on 2020-12-29 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tomat_fwd_chaining', '0005_delete_aturan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aturan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kebenaran_simpulan', models.CharField(choices=[('benar', 'ini benar'), ('salah', 'ini salah')], default='salah', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Penyakit',
            fields=[
                ('kode_penyakit', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AturanGejala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_aturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomat_fwd_chaining.aturan')),
                ('kode_gejala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomat_fwd_chaining.gejala')),
            ],
        ),
        migrations.AddField(
            model_name='aturan',
            name='penyakit_simpulan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomat_fwd_chaining.penyakit'),
        ),
    ]
